config/routes.rb
Listwalk::Application.routes.draw do
  root 'application#index'

  # Perform track search
  get 'search', to: 'search#result', as: 'new_playlist'

  # Playlist routes
  get 'open-playlist/:keyword', to: 'search#generate_playlist', as: 'generate_playlist'

  # Authenticate Spotify user via omniauth
  get 'auth/spotify', as: 'connect_to_spotify'
  get 'auth/spotify/callback', to: 'spotify_user#authenticate'
  get 'auth/spotify/disconnect', to: 'spotify_user#disconnect', as: 'disconnect_from_spotify'

  get '*path' => redirect('/')
end

app/models/search.rb
# Generates array of Spotify tracks based on valid
# keyword using rspotify gem
class Search < ActiveRecord::Base
    before_create :set_counter

    validates :keyword, presence: true
    validates :keyword, length: { minimum: 2}

    # Returns an array of tracks for given (valid) keyword
    def get_tracks!
        tracks = RSpotify::Track.search(self.keyword, limit: 50, offset: 0).sort_by(&:popularity)

        tracks.delete_if { |t| t.popularity < 50 }
        tracks = tracks.uniq { |t| t.artists.first.name }        

        raise 'The playlist could not be generated' if tracks.size < 4
        return tracks.reverse
    end

    # Create or re-create a Spotify playlist based upon tracks from a conducted search
    def get_playlist!(user, playlist_title)
        tracks = self.get_tracks!
        playlist = user.playlists.select { |p| p.name == playlist_title}


        if playlist.empty? 
            # Create new playlist
            playlist = user.create_playlist!(playlist_title)                    
            playlist.add_tracks!(tracks)              
        else    
            # Fetch pre-existing and replace tracks
            playlist = RSpotify::Playlist.find(user.id, playlist.first.id)
            playlist.replace_tracks!(tracks)
        end
        
        return playlist.uri
    end

    # @todo Do we really need this?
    def set_counter
        self.count = 1
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  helper_method :search_trends, :current_user

  # Utilized as helper method returning the current
  # authenticated Spotify user or nil
  def current_user
    if session[:spotify_user]
      @current_user ||= RSpotify::User.new(session[:spotify_user])
    else 
      @current_user = nil
    end
  end

  # The (5) most used search terms
  def search_trends
    Search.where('count > ? AND updated_at > ?', 10, Time.now - 10.days).take(5)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  # This is where keywords are sent
  def result
	    @search_term = Search.find_or_create_by!(keyword: params[:keyword].downcase)
	    @search_term.count += 1
	    @search_term.save	    
	    @playlist = @search_term.get_tracks!
      
      # Save latest search if user authenticates
      if current_user.nil?
        session[:last_search] = @search_term.keyword
      end

	    rescue
	    	flash[:notice] = "The list of tracks for '#{params[:keyword]}' was way to short or faulty, thus not created. Try something else :)"
        @search_term.delete

      redirect_to root_url
  end	

  # POST
  # Create or re-create a Spotify playlist given a title
  def generate_playlist
  		playlist = Search.find_or_create_by!(keyword: params[:keyword])
  		
  		redirect_to playlist.get_playlist!(current_user, "listwalk for #{params[:keyword]}")
  		# Sometimes, the access token cannot be verified
  		# thus throwing a 401 back. Redirect to index with proper notice
  		rescue   	
        if playlist 
          playlist.delete
        end
        flash[:notice] = "Something went wrong while generating playlist for #{params[:keyword]}..."
  			redirect_to root_url
  end
end

app/controllers/spotify_user_controller.rb
class SpotifyUserController < ApplicationController

	# Utilize rspotify (omniauth) for connecting to spotify
	# and storing the data as session based hash
	def authenticate
		if session[:spotify_user].nil?
			user = RSpotify::User.new(request.env['omniauth.auth'])
			session[:spotify_user] = user.to_hash
		end
			flash[:notice] = "Nice to see ya #{user.display_name}!"
		
		# Check if redirect
		if session[:last_search]
			save_keyword = session[:last_search]
			session[:last_search] = nil
			redirect_to new_playlist_url(keyword: save_keyword)
		else
			redirect_to root_url
		end
	end

	# No rocket science - just set session variable to nil
	def disconnect
		session[:spotify_user] = nil
		if flash[:notice].nil?
			flash[:notice] = "Disconnected from Spotify. Hope to see you soon!" 
		end
		redirect_to root_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<% content_for :meta_tags do %>
<title>Discover new music by keywords with listwalk</title>
<meta name="description" content="listwalk creates Spotify playlist based upon words rather than artist or song names. Enjoy a new, ingenious way of discovering music on Spotify.">
<!-- og tags -->
<meta property="og:site_name" content="listwalk">
<meta property="og:title" content="Discover new music on Spotify">
<meta property="og:description" content="While searching for music on Spotify, we are often limited by our preferences. listwalk lets you discover new music on an entirely different level!">
<meta property="og:type" content="website">
<meta property="og:url" content="<%= request.original_url %>">
<% end %>

<div class="row text-center">
<div class="col-sm-12">
    <h2 class="listwalk-type-green">This is how we do it</h2>
</div>
<div class="col-sm-3 col-sm-offset-1">
<h3><i class="fa fa-search"></i></h3>
<p>
Simply search for the first word that pops into your head.
</p>
</div>
<div class="col-sm-3 col-sm-offset-1">
<h3><i class="fa fa-circle-o-notch"></i></h3>
<p>We then find the best tracks based on your search term – no matter the genre!</p>
</div>
<div class="col-sm-3 col-sm-offset-1">
<h3><i class="fa fa-spotify"></i></h3>
<p></p>The playlist is now generated and available on your Spotify!<p></p>
</div>  

app/views/application/search.html.erb
<h2>
    listwalk for '<%= @keyword.keyword %>'
    <small><%= @keyword.count %></small> hits
</h2>

<% @playlist.each do |cover| %>
<img src="<%= cover.album.images.third['url'] %>">
<% end %>

<%= link_to "Open playlist '#{@keyword.keyword}'", generate_playlist_path(@keyword.keyword) %>

<% @playlist.each do |track| %>
    <li>
        <a href="<%= track.uri %>">Play</a>
        <%= track.name %>
        <small>by <%= track.artists.first.name %></small>
    </li>
<% end %>

<%= link_to "Open playlist '#{@keyword.keyword}'", generate_playlist_path(@keyword.keyword) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<%= yield(:meta_tags) %>
<!-- CDNs -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<!-- Favicon/touch icons -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<% if current_user %>
	<meta name="author" content="<%= current_user.display_name %>">
<% else %>
	<meta name="author" content="metsson">
<% end %>
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<!-- Apple -->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-touch-startup-image" href="/apple-startup.png">
<!-- Touch icons -->
<link rel="apple-touch-icon" href="/touch-icon-iphone.png">
<link rel="apple-touch-icon" sizes="76x76" href="/touch-icon-ipad.png">
<link rel="apple-touch-icon" sizes="120x120" href="/touch-icon-iphone-retina.png">
<link rel="apple-touch-icon" sizes="152x152" href="/touch-icon-ipad-retina.png">
<!-- Locals -->
<%= stylesheet_link_tag "application", media: "all" %>
<%= csrf_meta_tags %>
<meta name="fl-verify" content="03f223110f65aa0c2991d19032560aa5">
</head>
<body>
<% if flash[:notice] %>
<div class="notice">
	<p class="bg-primary">
	<%= flash[:notice] %></p>
</div>
<% end %>
<div id="fb-root"></div>
<!-- navigation links -->
<nav>	
	<ul class="list-inline">
		<% if current_user %>
		<li>
			<i class="fa fa-spotify"></i> Logged in via Spotify as <strong><%= current_user.display_name %></strong>
		</li>
		<li>				
			<i class="fa fa-sign-out"></i> <%= link_to 'Disconnect', disconnect_from_spotify_path %>
		</li>
		<% else %>
			<li><i class="fa fa-spotify"></i> <%= link_to 'Connect with Spotify', connect_to_spotify_path %></li>
		<% end %>		
	</ul>
</nav>
<div class="container">
	<header class="header">
		<h1>
		<%= link_to root_path do %>
		<span class="listwalk-type listwalk-type-green">listwalk</span> <small>New music. The ingenious way.		
		</small>	
		<% end %>	
		</h1>
	</header>
	<div class="search-and-trends">
		<form action="<%= new_playlist_path %>" method="get">		
			<input type="search" id="search" name="keyword" class="form-control" placeholder="Search for a word you are thinking of..." autofocus=autofocus value="<% if @search_term %><%= @search_term.keyword %><% end %>">
		</form>
		<% if !search_trends.empty? %>
		<aside class="trends">			
			<% # Top search keywords %>
			<ul class="list-inline">
			<li><strong><i class="fa fa-line-chart"></i> Trending </strong></li>
			<% search_trends.each do |trend| %>
			    <li><%= link_to trend.keyword, new_playlist_path(keyword: trend.keyword) %> <small>(<%= trend.count %></small> hits)</li>
			<% end %>
			</ul>
		</aside>
		<% end %>
	</div>	
	<div class="main-content">
		<%= yield %>
	</div>
</div>   
<div class="credits">
<p>
An <a href="https://github.com/metsson/listwalk" target="_blank">metsson</a> idea.<br>Data gathered from <a href="http://spotify.com" target="_blank">Spotify</a>.
</p>
</div>     	
<%= javascript_include_tag "application" %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50400145-3', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/search/result.html.erb
<% content_for :meta_tags do %>
<title>Playlist for '<%= @search_term.keyword %>' on listwalk</title>
<meta property="og:site_name" content="listwalk">
<meta name="description" content="Spotify playlist created for '<%= @search_term.keyword %>' using listwalk, containing the <%= @playlist.size %> most popular tracks, regardless of their genre. Enjoy!">
<!-- og tags -->
<meta property="og:title" content="Playlist for '<%= @search_term.keyword %>' on listwalk">
<meta property="og:description" content="Spotify playlist created for '<%= @search_term.keyword %>' using listwalk, containing the <%= @playlist.size %> most popular tracks, regardless of their genre. Enjoy!">
<meta property="og:type" content="music.playlist">
<meta property="og:url" content="<%= request.original_url %>">
<meta property="og:audio:type" content="audio/vnd.facebook.bridge">
<% @playlist.take(6).each do |cover| %>
	<% if cover.album.images.first %>
<meta property="og:image" content="<%= cover.album.images.first['url'] %>">
	<% end %>		
<% end %>
<% end %>
<div class="row">
	<div class="col-sm-8 playlist">
		<h2>
		    <span class="listwalk-type">listwalk</span> for '<%= @search_term.keyword %>'
		    <small><%= @playlist.size %> tracks</small>
		</h2>	
		<div class="fb-share-button" data-href="<%= request.original_url %>" data-layout="button_count"></div>
		<br>
		Want to find happinness in your daily life? <a href="http://puzzles.reflink.com/a16855" target="_blank">Find out how!</a>
		<ul class="list-inline">
		<% @playlist.each do |track| %>
		    <section>
			    <li>		        
			        <%= track.name %>
			        <small><%= track.artists.first.name %></small>
			    </li>
		    </section>
		<% end %>
		</ul>
	</div>
	<div class="col-sm-4 playlist-controls">
		<% if current_user %>			
			<%= link_to generate_playlist_path(@search_term.keyword) do %>
			<i class="fa fa-play"></i>  Play <span>(Opens in Spotify)</span>
			<% end %>
		<% else %>
			<%= link_to connect_to_spotify_path do %>
			<i class="fa fa-spotify"></i> Connect to listen!
			<% end %>
		<% end %>		
		<div class="playlist-cover">
		<% @playlist.take(6).each do |cover| %>
			<% if cover.album.images.third %>
				<img src="<%= cover.album.images.third['url'] %>">
			<% end %>		
		<% end %>
		</div>
	</div>	
</div>

app/views/search/search.html.erb
<h2>
    listwalk for '<%= @keyword.keyword %>'
    <small><%= @keyword.count %></small> hits
</h2>

<% @playlist.each do |cover| %>
<img src="<%= cover.album.images.third['url'] %>">
<% end %>

<% @playlist.each do |track| %>
    <li>
        <a href="<%= track.uri %>">Play</a>
        <%= track.name %>
        <small>by <%= track.artists.first.name %></small>
    </li>
<% end %>